version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: avneendrakanva/reverseproxy 
  backend_user:
    build:
      context: ../../udagram-users-api
    image: avneendrakanva/udagram-users-api
  backend_feed:
    build:
      context: ../../udagram-feed-api  
    image: avneendrakanva/udagram-feed-api
  frontend:
    build:
      context: ../../udagram-frontend  
    image: avneendrakanva/udagram-frontend:local
