version: "3"
services:
  reverseproxy:
      image: avneendrakanva/reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed     
  backend-user:
    image: avneendrakanva/udagram-users-api
    environment:
      POSTGRESS_USERNAME: udagramkanvadev
      POSTGRESS_PASSWORD: Cheekushake#0708  
      POSTGRESS_DB: udagramkanvadev 
      POSTGRESS_HOST: udagramkanvadev.c3nxmxqvxtqd.us-east-2.rds.amazonaws.com  
      AWS_REGION: us-east-2 
      AWS_PROFILE: default 
      AWS_BUCKET: udagram-kanva-dev
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  backend-feed:
    image: avneendrakanva/udagram-feed-api
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRESS_USERNAME: udagramkanvadev
      POSTGRESS_PASSWORD: Cheekushake#0708 
      POSTGRESS_DB:  udagramkanvadev
      POSTGRESS_HOST: udagramkanvadev.c3nxmxqvxtqd.us-east-2.rds.amazonaws.com 
      AWS_REGION: us-east-2 
      AWS_PROFILE: default 
      AWS_BUCKET: udagram-kanva-dev
      JWT_SECRET: helloworld
      URL: "http://localhost:8100"
  frontend:
    image: avneendrakanva/udagram-frontend:local
    ports:
      - "8100:80"
